# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1386625919);
user_pref("app.update.lastUpdateTime.background-update-timer", 1386625799);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1386626113);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1386690602);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1386691256);
user_pref("app.update.migrated.updateDir", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.link.open_newwindow", 2);
user_pref("browser.migration.version", 14);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.privatebrowsing.autostart", true);
user_pref("browser.rights.3.shown", true);
user_pref("browser.sessionstore.restore_on_demand", false);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20131112160018");
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.slowStartup.averageTime", 2854);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage", "about:blank");
user_pref("browser.startup.homepage_override.buildID", "20131007042817");
user_pref("browser.startup.homepage_override.mstone", "24.0");
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.tabs.warnOnOpen", false);
user_pref("browser.taskbar.lastgroupid", "E7CF176E110C211B");
user_pref("browser.urlbar.autocomplete.enabled", false);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1386711790794");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1386691199102");
user_pref("datareporting.policy.firstRunTime", "1386625390793");
user_pref("datareporting.sessions.current.activeTicks", 1);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.main", 1653);
user_pref("datareporting.sessions.current.startTime", "1386691530157");
user_pref("datareporting.sessions.current.totalTime", 6);
user_pref("datareporting.sessions.currentIndex", 7);
user_pref("datareporting.sessions.previous.0", "{\"s\":1386625390068,\"a\":3,\"t\":22,\"c\":true,\"m\":52,\"fp\":3207,\"sr\":4056}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1386625430788,\"a\":4,\"t\":114,\"c\":true,\"m\":94,\"fp\":1836,\"sr\":1867}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1386625559056,\"a\":55,\"t\":431,\"c\":true,\"m\":132,\"fp\":1151,\"sr\":1181}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1386625989760,\"a\":39,\"t\":420,\"c\":true,\"m\":1740,\"fp\":4745,\"sr\":4806}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1386626424890,\"a\":11,\"t\":189,\"c\":true,\"m\":2,\"fp\":1258,\"sr\":21612}");
user_pref("datareporting.sessions.previous.5", "{\"s\":1386690396266,\"a\":3,\"t\":237,\"c\":true,\"m\":25449,\"fp\":70437,\"sr\":96072}");
user_pref("datareporting.sessions.previous.6", "{\"s\":1386691136175,\"a\":14,\"t\":223,\"c\":true,\"m\":74,\"fp\":1379,\"sr\":1414}");
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.bootstrappedAddons", "{\"firebug@software.joehewitt.com\":{\"version\":\"1.12.5\",\"type\":\"extension\",\"descriptor\":\"C:\\\\Users\\\\pwroe\\\\Dropbox\\\\workspace\\\\SeleniumTesting\\\\profiles\\\\firefoxProfiles\\\\extensions\\\\firebug@software.joehewitt.com.xpi\"}}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "autoauth%40efinke.com:2.1,FireXPath%40pierre.tholence.com:0.9.7,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:24.0");
user_pref("extensions.firebug.currentVersion", "1.12.5");
user_pref("extensions.firebug.toolbarCustomizationDone", true);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20130826.01");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"C:\\\\Program Files\\\\Waterfox\\\\browser\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1383087544784,\"rdfTime\":1381118788000}}},{\"name\":\"winreg-app-user\",\"addons\":{\"{B21F5E31-B8E8-41CD-B74C-168A71A10E49}\":{\"descriptor\":\"C:\\\\Users\\\\pwroe\\\\AppData\\\\Local\\\\GreatArcadeHits\\\\gahff.xpi\",\"mtime\":1384964168743}}},{\"name\":\"app-profile\",\"addons\":{\"autoauth@efinke.com\":{\"descriptor\":\"C:\\\\Users\\\\pwroe\\\\Dropbox\\\\workspace\\\\SeleniumTesting\\\\profiles\\\\firefoxProfiles\\\\extensions\\\\autoauth@efinke.com.xpi\",\"mtime\":1386625992166},\"firebug@software.joehewitt.com\":{\"descriptor\":\"C:\\\\Users\\\\pwroe\\\\Dropbox\\\\workspace\\\\SeleniumTesting\\\\profiles\\\\firefoxProfiles\\\\extensions\\\\firebug@software.joehewitt.com.xpi\",\"mtime\":1386626473797},\"FireXPath@pierre.tholence.com\":{\"descriptor\":\"C:\\\\Users\\\\pwroe\\\\Dropbox\\\\workspace\\\\SeleniumTesting\\\\profiles\\\\firefoxProfiles\\\\extensions\\\\FireXPath@pierre.tholence.com.xpi\",\"mtime\":1386690447977}}}]");
user_pref("extensions.lastAppVersion", "24.0");
user_pref("extensions.lastPlatformVersion", "24.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://search/firepath");
user_pref("extensions.ui.locale.hidden", true);
user_pref("gecko.buildID", "20131007042817");
user_pref("gecko.mstone", "24.0");
user_pref("gfx.direct3d.last_used_feature_level_idx", 0);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.migrated", true);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("toolkit.startup.last_success", 1386691531);
user_pref("toolkit.telemetry.previousBuildID", "20131007042817");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1389217398);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
